baseurl = "/"
languageCode = "en-us"
title = "Test & Optimize Blog"
theme = "hugo-theme-casper"
disqusShortname = "getoptimise"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "YAP SHIAO SHYAN"
  authorlocation = "Dublin, Ireland"
  authorwebsite = "https://www.testandoptimize.com"
  bio= "Based in Ireland, I help online business turn clicks into profits"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  #githubName = "vjeantet"
  twitterName = "testandoptimize"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
